//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Divination.ACT.DiscordIntegration.Properties {
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Divination.ACT.DiscordIntegration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ALLIANCE PARTY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartyAllianceParty {
            get {
                return ResourceManager.GetString("PartyAllianceParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FULL PARTY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartyFullParty {
            get {
                return ResourceManager.GetString("PartyFullParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LIGHT PARTY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartyLightParty {
            get {
                return ResourceManager.GetString("PartyLightParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SOLO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartySolo {
            get {
                return ResourceManager.GetString("PartySolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチ済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessAttached {
            get {
                return ResourceManager.GetString("ProcessAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}.exe (PID: {1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未アタッチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessNotAttached {
            get {
                return ResourceManager.GetString("ProcessNotAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessNotFound {
            get {
                return ResourceManager.GetString("ProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戦闘中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusInCombat {
            get {
                return ResourceManager.GetString("StatusInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusInTitleScreen {
            get {
                return ResourceManager.GetString("StatusInTitleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランチャー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusLauncher {
            get {
                return ResourceManager.GetString("StatusLauncher", resourceCulture);
            }
        }
    }
}
