name: CI

on:
  push:
    branches-ignore:
      - 'renovate/**'

  pull_request:
    types:
      - opened
      - synchronize
    branches-ignore:
      - 'renovate/**'

  release:
    types:
      - created

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # GitVersion
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        if: github.event_name != 'pull_request'
        run: |
          dotnet pack --configuration Release --include-source
          dotnet nuget push */bin/x64/Release/*.symbols.nupkg `
            --source https://api.nuget.org/v3/index.json `
            --api-key ${{ secrets.NUGET_API_KEY }} `
            --skip-duplicate

  format:
    if: github.event_name == 'push'
    uses: SlashNephy/.github/.github/workflows/dotnet-format.yml@master
    permissions:
      contents: write
