name: 'Format Plugin Manifest'

on:
  workflow_call:
    inputs:
      plugin-name:
        required: true
        type: string
      dotnet-version:
        required: false
        type: string
        default: '6.0.x'
      commit-message:
        required: false
        type: string
        default: '🧹 format manifest'

permissions:
  contents: 'write'

jobs:
  format-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Checkout Repository (Common)
        uses: actions/checkout@v3
        with:
          repository: 'horoscope-dev/Dalamud.Divination.Common'
          path: 'Common'
          token: '${{ secrets.GITHUB_TOKEN }}'
          # GitVersion
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Format
        run: dotnet run --project Dalamud.JsonFormatter
        working-directory: 'Common'
        env:
          PLUGIN_JSON_PATH: '..\${{ inputs.plugin-name }}\${{ inputs.plugin-name }}.json'
