name: 'Deploy Plugin'

on:
  workflow_call:
    inputs:
      plugin-name:
        required: true
        type: string
      plugin-repository:
        required: false
        type: string
        default: 'horoscope-dev/Dalamud.DivinationPluginRepo'
    secrets:
      DEPLOY_GITHUB_TOKEN:
        required: true

permissions:
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@v3
        with:
          repository: '${{ inputs.plugin-repository }}'
          token: '${{ secrets.DEPLOY_GITHUB_TOKEN }}'

      - name: Download Artifact (release)
        uses: actions/download-artifact@v3
        with:
          name: '${{ inputs.plugin-name }}'
          path: 'dist/testing/${{ inputs.plugin-name }}'

      - name: Download Artifact (gitversion.json)
        uses: actions/download-artifact@v3
        with:
          name: 'gitversion.json'
          path: 'gitversion'

      - name: Read InformationalVersion
        id: version
        run: |
          value=$(cat gitversion/gitversion.json | jq .InformationalVersion)
          rm -rf gitversion
          echo "value=$value" >> $GITHUB_OUTPUT

      - name: Prepare commits.json
        run: |
          curl \
            -o dist/testing/${{ inputs.plugin-name }}/commits.json \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DEPLOY_GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/commits

      - name: Prepare event.json
        run: echo '${{ toJSON(github.event) }}' > dist/testing/${{ inputs.plugin-name }}/event.json

      - name: Copy Artifact (stable)
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: cp -rf dist/testing/${{ inputs.plugin-name }} dist/stable/${{ inputs.plugin-name }}

      - name: Push to Plugin Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        continue-on-error: true
        with:
          commit_message: 'Deploy ${{ inputs.plugin-name }} ${{ steps.version.outputs.value }}'
