name: Build (Common)

on:
  push:
    paths:
      - Common/**
      - Directory.Build.props
    branches:
      - master
  pull_request:
    paths:
      - Common/**
      - Directory.Build.props
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          # GitVersion
          fetch-depth: 0

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/${env:DALAMUD_BRANCH}/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
        env:
          DALAMUD_BRANCH: stg

      - name: Build
        run: dotnet build --configuration Release
        working-directory: Common
