name: Docker

on:
  push:
    paths-ignore:
      - '**.md'

  release:
    types:
      - published

  workflow_dispatch:

env:
  DOCKER_BASE_NAME: ghcr.io/SlashNephy/divination-sse-server
  PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64/v8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Prepare image tag (master)
        if: github.ref == 'refs/heads/master'
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV
      - name: Prepare image tag (other branches)
        if: github.ref != 'refs/heads/master'
        run: echo "DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Prepare image tag (Release)
        if: github.event_name == 'release'
        run: echo "DOCKER_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          build-args: BUILDKIT_INLINE_CACHE=1
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.DOCKER_BASE_NAME }}:${{ env.DOCKER_TAG }}
          cache-from: ${{ env.DOCKER_BASE_NAME }}:${{ env.DOCKER_TAG }}
