name: 'Deploy Plugin'

on:
  workflow_call:
    inputs:
      plugin-name:
        required: true
        type: string
      plugin-repository:
        required: false
        type: string
        default: 'SlashNephy/divination-distrib'
    secrets:
      DEPLOY_GITHUB_TOKEN:
        required: true

permissions:
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: '${{ inputs.plugin-repository }}'
          token: '${{ secrets.DEPLOY_GITHUB_TOKEN }}'

      - name: Download Artifact (release)
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: '${{ inputs.plugin-name }}'
          path: 'plugins/testing/${{ inputs.plugin-name }}'

      - name: Download Artifact (gitversion.json)
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: '${{ inputs.plugin-name }}-GitVersion'
          path: 'gitversion'

      - name: Read InformationalVersion
        id: version
        run: |
          value=$(cat gitversion/gitversion.json | jq .InformationalVersion)
          rm -rf gitversion
          echo "value=$value" >> $GITHUB_OUTPUT

      - name: Prepare commits.json
        run: |
          curl \
            -o plugins/testing/${{ inputs.plugin-name }}/commits.json \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DEPLOY_GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/commits

      - name: Prepare event.json
        run: echo "$EVENT_JSON" | jq -c > plugins/testing/${{ inputs.plugin-name }}/event.json
        env:
          EVENT_JSON: ${{ toJSON(github.event) }}

      - name: Copy Artifact (stable)
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p plugins/stable/${{ inputs.plugin-name }}
          cp -rf plugins/testing/${{ inputs.plugin-name }}/* plugins/stable/${{ inputs.plugin-name }}

      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          commit-message: '⚙️ Deploy ${{ inputs.plugin-name }} ${{ steps.version.outputs.value }}'
          author: StarryBlueSky-bot <97773209+StarryBlueSky-bot@users.noreply.github.com>
          branch: ci/update-plugin-master
          branch-suffix: random
          delete-branch: true
          title: '⚙️ Deploy ${{ inputs.plugin-name }} ${{ steps.version.outputs.value }}'

      - name: Automerge
        if: steps.create-pull-request.outputs.pull-request-number
        run: gh pr merge --repo ${PLUGIN_REPOSITORY} --squash ${PR_NUMBER}
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          PLUGIN_REPOSITORY: ${{ inputs.plugin-repository }}
          PR_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
